substitutions:
  _REGION: asia-south1
  _REPOSITORY: backend-repo
  _IMAGE: backend-api
  _SERVICE: backend-service

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE
      - ./server

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
