substitutions:
  _SERVICE_NAME: "trekkers-heaven"
  _REGION: "asia-south1"

steps:
- name: "node:18"
  id: "Build client"
  entrypoint: "bash"
  args:
  - -c
  - |
    set -e
    cd client
    npm ci
    npm run build
    rm -rf ../server/public || true
    mkdir -p ../server/public
    cp -r dist/* ../server/public/

- name: "gcr.io/cloud-builders/docker"
  id: "Build image"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA", "server"]

- name: "gcr.io/cloud-builders/docker"
  id: "Push image"
  args: ["push", "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"]

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: "Deploy to Cloud Run"
  entrypoint: "bash"
  args:
  - -c
  - |
    set -e
    gcloud run deploy $_SERVICE_NAME \
      --image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA \
      --region=$_REGION \
      --platform=managed \
      --allow-unauthenticated \
      --set-env-vars=NODE_ENV=production

images:
- "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"

timeout: "1200s"

serviceAccount: projects/$PROJECT_ID/serviceAccounts/56183528744-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

Location: Repository
Cloud Build config file: cloudbuild.yaml
